services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:17
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME} -d rivenbot"]
      interval: 5s
      timeout: 3s
      retries: 5
    command: ["postgres"]
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: rivenbot
    ports:
      - "5432:5432"
  redis:
    container_name: redis
    hostname: redis
    image: redis:8
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "6379:6379"
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:management
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 3
    ports:
      - "5672:5672"
      - "15672:15672"
  crawler:
    container_name: crawler
    hostname: crawler
    build:
      context: .
      tags:
        - "crawler:latest"
      args:
        SERVICE: crawler
    depends_on:
      rabbitmq:
        condition: service_healthy
  proxy:
    build:
      contex: .
      tags:
        - "proxy-service:latest"
      args:
        SERVICE: proxy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
  processor:
    build:
      context: .
      tags:
        - "processing-service:latest"
      args:
        SERVICE: processor
    # I know its unsafe, its just for development =)
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: processor
    hostname: processor
    depends_on:
        postgres:
          condition: service_healthy
        redis:
          condition: service_healthy
        rabbitmq:
          condition: service_healthy
    develop:
      watch:
        - path: .
          action: rebuild
