// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.claimLogEntryForProcessingStmt, err = db.PrepareContext(ctx, claimLogEntryForProcessing); err != nil {
		return nil, fmt.Errorf("error preparing query ClaimLogEntryForProcessing: %w", err)
	}
	if q.createDestinyPlayerStmt, err = db.PrepareContext(ctx, createDestinyPlayer); err != nil {
		return nil, fmt.Errorf("error preparing query CreateDestinyPlayer: %w", err)
	}
	if q.createInstanceStmt, err = db.PrepareContext(ctx, createInstance); err != nil {
		return nil, fmt.Errorf("error preparing query CreateInstance: %w", err)
	}
	if q.createInstanceCharacterStmt, err = db.PrepareContext(ctx, createInstanceCharacter); err != nil {
		return nil, fmt.Errorf("error preparing query CreateInstanceCharacter: %w", err)
	}
	if q.createInstanceCharacterWeaponStmt, err = db.PrepareContext(ctx, createInstanceCharacterWeapon); err != nil {
		return nil, fmt.Errorf("error preparing query CreateInstanceCharacterWeapon: %w", err)
	}
	if q.createInstancePlayerStmt, err = db.PrepareContext(ctx, createInstancePlayer); err != nil {
		return nil, fmt.Errorf("error preparing query CreateInstancePlayer: %w", err)
	}
	if q.createLogEntryStmt, err = db.PrepareContext(ctx, createLogEntry); err != nil {
		return nil, fmt.Errorf("error preparing query CreateLogEntry: %w", err)
	}
	if q.createPgcrStmt, err = db.PrepareContext(ctx, createPgcr); err != nil {
		return nil, fmt.Errorf("error preparing query CreatePgcr: %w", err)
	}
	if q.createWeaponStmt, err = db.PrepareContext(ctx, createWeapon); err != nil {
		return nil, fmt.Errorf("error preparing query CreateWeapon: %w", err)
	}
	if q.incrementPlayerCountsStmt, err = db.PrepareContext(ctx, incrementPlayerCounts); err != nil {
		return nil, fmt.Errorf("error preparing query IncrementPlayerCounts: %w", err)
	}
	if q.updateLogEntryStatusStmt, err = db.PrepareContext(ctx, updateLogEntryStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateLogEntryStatus: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.claimLogEntryForProcessingStmt != nil {
		if cerr := q.claimLogEntryForProcessingStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing claimLogEntryForProcessingStmt: %w", cerr)
		}
	}
	if q.createDestinyPlayerStmt != nil {
		if cerr := q.createDestinyPlayerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createDestinyPlayerStmt: %w", cerr)
		}
	}
	if q.createInstanceStmt != nil {
		if cerr := q.createInstanceStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createInstanceStmt: %w", cerr)
		}
	}
	if q.createInstanceCharacterStmt != nil {
		if cerr := q.createInstanceCharacterStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createInstanceCharacterStmt: %w", cerr)
		}
	}
	if q.createInstanceCharacterWeaponStmt != nil {
		if cerr := q.createInstanceCharacterWeaponStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createInstanceCharacterWeaponStmt: %w", cerr)
		}
	}
	if q.createInstancePlayerStmt != nil {
		if cerr := q.createInstancePlayerStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createInstancePlayerStmt: %w", cerr)
		}
	}
	if q.createLogEntryStmt != nil {
		if cerr := q.createLogEntryStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createLogEntryStmt: %w", cerr)
		}
	}
	if q.createPgcrStmt != nil {
		if cerr := q.createPgcrStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createPgcrStmt: %w", cerr)
		}
	}
	if q.createWeaponStmt != nil {
		if cerr := q.createWeaponStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createWeaponStmt: %w", cerr)
		}
	}
	if q.incrementPlayerCountsStmt != nil {
		if cerr := q.incrementPlayerCountsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing incrementPlayerCountsStmt: %w", cerr)
		}
	}
	if q.updateLogEntryStatusStmt != nil {
		if cerr := q.updateLogEntryStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateLogEntryStatusStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                                DBTX
	tx                                *sql.Tx
	claimLogEntryForProcessingStmt    *sql.Stmt
	createDestinyPlayerStmt           *sql.Stmt
	createInstanceStmt                *sql.Stmt
	createInstanceCharacterStmt       *sql.Stmt
	createInstanceCharacterWeaponStmt *sql.Stmt
	createInstancePlayerStmt          *sql.Stmt
	createLogEntryStmt                *sql.Stmt
	createPgcrStmt                    *sql.Stmt
	createWeaponStmt                  *sql.Stmt
	incrementPlayerCountsStmt         *sql.Stmt
	updateLogEntryStatusStmt          *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                                tx,
		tx:                                tx,
		claimLogEntryForProcessingStmt:    q.claimLogEntryForProcessingStmt,
		createDestinyPlayerStmt:           q.createDestinyPlayerStmt,
		createInstanceStmt:                q.createInstanceStmt,
		createInstanceCharacterStmt:       q.createInstanceCharacterStmt,
		createInstanceCharacterWeaponStmt: q.createInstanceCharacterWeaponStmt,
		createInstancePlayerStmt:          q.createInstancePlayerStmt,
		createLogEntryStmt:                q.createLogEntryStmt,
		createPgcrStmt:                    q.createPgcrStmt,
		createWeaponStmt:                  q.createWeaponStmt,
		incrementPlayerCountsStmt:         q.incrementPlayerCountsStmt,
		updateLogEntryStatusStmt:          q.updateLogEntryStatusStmt,
	}
}
